[package]
name = "polymanager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
facet = "0.27.16"
facet-toml = "0.25.18"
ratatui = "0.29.0"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "fs", "signal", "time", "process", "full"] }
